spring:
  application:
    name: githubfetcher
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:scm_analyzer}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

githubfetcher:
  github:
    token: Bearer ${GITHUB_TOKEN}
    numberOfRequest: 4000
    mq:
      producer:
        topic: github_repos
